name: Build and Deploy to Docker Registry
run-name: ${{ github.actor }} is run CI/CD pipeline 🚀

on:
    push:
        branches: [ main ]
        paths:
            - 'docker-deploy.yml'
            - 'platform/chart/**'
            - 'platform/docker/**'
            - 'werf.yml'

    workflow_dispatch:

jobs:
    werf-steps:

        permissions:
            contents: read
            packages: write

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v5
                with:
                    submodules: recursive
                    fetch-depth: 0

            -   name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Install werf
                uses: werf/actions/install@v2
